In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

tillage = pd.read_excel("/content/prod_views_data_viewld_operations_tillage.xlsx")
tillage.head()
tillage.info()
#tillage= tillage.drop_duplicates(subset='farm_season_field_id', keep='last')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   farm_id                    217 non-null    int64
 1   farm_name                  217 non-null    object
 2   farm_season_id             217 non-null    int64
 3   season                     217 non-null    object
 4   farm_season_field_id       217 non-null    int64
 5   farm_season_field_name     217 non-null    object
 6   farm_season_field_crop_id  217 non-null    int64
 7   crop_id                    217 non-null    int64
 8   crop_name                  217 non-null    object
 9   tillage_id                 217 non-null    int64
 10  tillage_name               217 non-null    object
 11  machinery                  177 non-null    object
 12  number_of_passes           217 non-null    int64
dtypes: int64(7), object(6)
memory usage: 22.2+ KB

In [20]:
tillage['farm_season_field_id'].nunique()

130

In [25]:
tillage = tillage.drop_duplicates()
tillage

,farm_id,farm_name,farm_season_id,season,farm_season_field_id,farm_season_field_name,farm_season_field_crop_id,crop_id,crop_name,tillage_id,tillage_name,machinery,number_of_passes
0,1555,GFA Moulas,1208,2020-2021,16515,Champ 0,16311,192,Permanent pasture,4,no tillage,NaN,0
1,1555,GFA Moulas,1208,2020-2021,16516,SB,16020,73,Grain corn,2,reduced till,Shredder,1
2,1555,GFA Moulas,1208,2020-2021,16516,SB,16020,73,Grain corn,2,reduced till,Shallow tillage (<10cm),2
3,1555,GFA Moulas,1208,2020-2021,16517,Champ 2,16021,192,Permanent pasture,4,no tillage,NaN,0
4,1555,GFA Moulas,1208,2020-2021,16518,POMP,16022,49,Durum winter wheat,1,conventional till,Plough,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,1555,GFA Moulas,7283,2023-2024,360944,Trame,361847,73,Grain corn,2,reduced till,Shredder,1
213,1555,GFA Moulas,7283,2023-2024,360945,LONG 1,361848,73,Grain corn,2,reduced till,Shredder,1
214,1555,GFA Moulas,7283,2023-2024,360945,LONG 1,361848,73,Grain corn,2,reduced till,Shallow tillage (<10cm),3
215,1555,GFA Moulas,7283,2023-2024,360946,LONG 2,361849,73,Grain corn,2,reduced till,Shallow tillage (<10cm),3
216,1555,GFA Moulas,7283,2023-2024,360946,LONG 2,361849,73,Grain corn,2,reduced till,Shredder,1

In [26]:
tillage.columns

Index(['farm_id', 'farm_name', 'farm_season_id', 'season',
       'farm_season_field_id', 'farm_season_field_name',
       'farm_season_field_crop_id', 'crop_id', 'crop_name', 'tillage_id',
       'tillage_name', 'machinery', 'number_of_passes'],
      dtype='object')

In [27]:
tillage['number_of_passes'].nunique()

4

In [28]:
# Keep only relevant columns
tillage = tillage[['farm_season_field_id', 'number_of_passes']]

In [29]:
tillage.to_csv("eda_tillage.csv", index=False)